inherit_gem:
  rubocop-shopify: rubocop.yml

inherit_mode:
  merge:
    - Include

AllCops:
  Include:
    - '**/*.gemfile'
Lint/SuppressedException:
  Exclude:
    - lib/job-iteration.rb
Naming/FileName:
  Exclude:
    - lib/job-iteration.rb
