inherit_gem:
  rubocop-shopify: rubocop.yml

inherit_mode:
  merge:
    - Include

AllCops:
  TargetRubyVersion: 2.6
  Include:
    - '**/*.gemfile'
Lint/SuppressedException:
  Exclude:
    - lib/job-iteration.rb
Style/GlobalVars:
  Exclude:
    - lib/job-iteration/integrations/resque.rb
Naming/FileName:
  Exclude:
    - lib/job-iteration.rb
Style/MethodCallWithArgsParentheses:
  Exclude:
    - "gemfiles/*"
    - Gemfile
