# frozen_string_literal: true

# $LOAD_PATH.unshift File.dirname(__FILE__) + '/../../lib'
# $LOAD_PATH.unshift File.dirname(__FILE__) unless $LOAD_PATH.include?(File.dirname(__FILE__))
require "resque/tasks"

require "logger"
require "job-iteration"
require "i18n"

require_relative "../jobs"

redis_url = ENV.fetch("REDIS_URL") { "redis://localhost:6379/0" }
Resque.redis = redis_url

I18n.available_locales = [:en]
ActiveJob::Base.queue_adapter = :resque
