# frozen_string_literal: true

# $LOAD_PATH.unshift File.dirname(__FILE__) + '/../../lib'
# $LOAD_PATH.unshift File.dirname(__FILE__) unless $LOAD_PATH.include?(File.dirname(__FILE__))
require "resque/tasks"

require "job-iteration"
require "job-iteration/integrations/resque"
require "active_job"
require "i18n"

require_relative "../jobs"

redis_url = if ENV["USING_DEV"] == "1"
  "job-iteration.railgun:6379"
elsif ENV['REDIS_HOST']
  "#{ENV['REDIS_HOST']}:6379"
else
  "localhost:6379"
end

Resque.redis = redis_url

I18n.available_locales = [:en]
ActiveJob::Base.queue_adapter = :resque
